/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan.pratikum;

import javax.swing.JOptionPane;

/**
 *
 * @author elvina
 */
public class ProgramAritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;

    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        Panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        ButtonHasil = new javax.swing.JButton();
        ket = new javax.swing.JLabel();
        tHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 20, 150, 30);

        jLabel2.setText("Jenis Aritmatika");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 100, 100, 14);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(450, 90, 150, 30);

        Panel.setBackground(new java.awt.Color(204, 255, 204));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        Panel.setLayout(null);

        jLabel3.setText("Jumlah Bilangan");
        Panel.add(jLabel3);
        jLabel3.setBounds(30, 80, 100, 20);

        bil4.setText("Bilangan 4");
        Panel.add(bil4);
        bil4.setBounds(30, 240, 80, 20);

        bil1.setText("Bilangan 1");
        Panel.add(bil1);
        bil1.setBounds(30, 120, 80, 20);

        bil2.setText("Bilangan 2");
        Panel.add(bil2);
        bil2.setBounds(30, 160, 80, 20);

        bil3.setText("Bilangan 3");
        Panel.add(bil3);
        bil3.setBounds(30, 200, 80, 20);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih salah satu", "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        Panel.add(pilihanbil);
        pilihanbil.setBounds(310, 80, 140, 30);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        Panel.add(b1);
        b1.setBounds(310, 120, 140, 30);
        Panel.add(b2);
        b2.setBounds(310, 160, 140, 30);
        Panel.add(b3);
        b3.setBounds(310, 200, 140, 30);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        Panel.add(b4);
        b4.setBounds(310, 240, 140, 30);

        ButtonHasil.setText("HITUNG");
        ButtonHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHasilActionPerformed(evt);
            }
        });
        Panel.add(ButtonHasil);
        ButtonHasil.setBounds(313, 290, 120, 23);

        ket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Panel.add(ket);
        ket.setBounds(170, 20, 200, 30);
        Panel.add(tHasil);
        tHasil.setBounds(190, 350, 280, 80);

        jPanel1.add(Panel);
        Panel.setBounds(90, 130, 520, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 630);

        setBounds(0, 0, 707, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void ButtonHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHasilActionPerformed
        Double hsl = 0.0;

        Double a1, a2, a3 = null, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());

        if (jns.equals("Penjumlahan")){
            if (jml == 2){
                hsl = a1+a2;
                tHasil.setText(""+a1+ " + " +a2+ " = " +hsl);
            }

            if (jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1+a2+a3;
                tHasil.setText(""+a1+ " + " + a2 + " + " + a3 + " = " + hsl);
            }

            if (jml == 4){
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1+a2+a3+a4;
                tHasil.setText(""+a1+ " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }

        if (jns.equals("Pengurangan")){
            if (jml == 2) {
                hsl = a1 - a2;
                tHasil.setText(""+a1 + " - " + a2 + " = " + hsl);
            }

            if (jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1-a2-a3;
                tHasil.setText(""+a1+ " - " + a2 + " - " + a3 + " = " + hsl);
            }

            if (jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1-a2-a3-a4;
                tHasil.setText(""+a1+ " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }}

            if (jns.equals("Perkalian")){
                if (jml == 2) {
                    hsl = a1 * a2;
                    tHasil.setText(""+a1 + " x " + a2 + " = " + hsl);
                }

                if (jml == 3){
                    a3 = Double.parseDouble(b3.getText().toString());
                    hsl = a1*a2*a3;
                    tHasil.setText(""+a1+ " x " + a2 + " x " + a3 + " = " + hsl);
                }

                if (jml == 4){
                    a3 = Double.parseDouble(b3.getText().toString());
                    a4 = Double.parseDouble(b4.getText().toString());
                    hsl = a1*a2*a3*a4;
                    tHasil.setText(""+a1+ " x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
                }}

                if (jns.equals("Pembagian")){
                    if (jml == 2) {
                        hsl = a1/a2;
                        tHasil.setText(""+a1 + " : " + a2 + " = " + hsl);

                    }

                    if (jml == 3){
                        a3 = Double.parseDouble(b3.getText().toString());
                        hsl = a1/a2/a3;
                        tHasil.setText(""+a1+ " : " + a2 + " : " + a3 + " = " + hsl);
                    }

                    if (jml == 4){
                        a3 = Double.parseDouble(b3.getText().toString());
                        a4 = Double.parseDouble(b4.getText().toString());
                        hsl = a1/a2/a3/a4;
                        tHasil.setText(""+a1+ " : " + a2 + " : " + a3 + " : " + a4 + " = " + hsl);
                    } }
                    // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHasil;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField tHasil;
    // End of variables declaration//GEN-END:variables

    private void getJumlah() {
       if(pilihanbil.getSelectedItem().equals("2"))
            {
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2;
            }
            else if (pilihanbil.getSelectedItem().equals("3"))
            {
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 3;
            }
            else if (pilihanbil.getSelectedItem().equals("4"))
            {
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 4;
            }
    }

    private void setJenis() {
        if (jenis.getSelectedItem().equals("Penjumlahan")){
        jns = "Penjumlahan";
        ket.setText("Penjumlahan");
        Panel.setVisible(true);
        pilihanbil.setEnabled(true);

        }
        else if (jenis.getSelectedItem().equals("Pengurangan"))
        {
            jns = "Pengurangan";
        ket.setText("Pengurangan");
        Panel.setVisible(true);
        pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
        ket.setText("Perkalian");
        Panel.setVisible(true);
        pilihanbil.setEnabled(true);

        }
        else if (jenis.getSelectedItem().equals("Pembagian")){
            jns = "Penmbagian";
        ket.setText("Pembagian");
        Panel.setVisible(true);
        pilihanbil.setEnabled(true);
}
    }
}
